### ISSUE TITLE
Issue install mdEditor on Ubuntu 16-04 (and Mac OS X)

### ISSUE THREAD

**Issue by pulsifer** [adiwg/mdEditor#60]
Hi,

I have installed mdEditor (App Version: 0.0.0+2c2ea582) on Ubuntu 16-04.  The install seemed to succeed, however when accessing the application, no metadata fields are visible (see screen cap).  A warning message is presented in the console, but it does not seem to be related:

vendor.js:17266DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:17248:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17358:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:17278:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17358:7)
        at invoke (http://localhost:4200/assets/vendor.js:17374:7)
        at deprecate (http://localhost:4200/assets/vendor.js:17342:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:30207:37)
        at Module.callback (http://localhost:4200/assets/vendor.js:159591:21)
        at Module.exports (http://localhost:4200/assets/vendor.js:140:32)

I am having the same experience with a local install on Mac OS X 10.11.6

![image](https://cloud.githubusercontent.com/assets/2481688/21151052/27878070-c12f-11e6-8b17-656b2d7875fc.png)

Have you seen similar behavior? Thoughts on possible causes or troubleshooting approaches?

**Comment by jlblcc** [comment]
Looks like you have everything installed and running correctly. There are no forms for the _Metadata Records_ routes yet. We've been waiting until v2 of the [adiwg/mdJson-schemas](https://github.com/adiwg/mdJson-schemas) is ready to start building those forms.  Content in those sections should start appearing over the next month or so.

Sorry for the confusion. Maybe we should be more explicit about this in the initial warning popup?

**Comment by pulsifer** [comment]
Thanks, Josh.  Good to know that the install was successful.  I like the easy install process using node, npm, etc..  A more detailed message with estimated dates would be helpful, even if it is in the form of "Q1" or "Q2".  We are keen to test the tool on ELOKA-related projects.  Appears to have great potential!
